# Generated by Django 4.1.3 on 2023-03-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="valor_inicial",
            new_name="valor",
        ),
    ]
