# Generated by Django 4.1.3 on 2023-03-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="watch_list",
        ),
    ]
