# Generated by Django 4.1.3 on 2023-03-07 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_auctionlisting_watch_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="precio",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(9999999999),
                ]
            ),
        ),
    ]
